/*
# Test the Server API
*/
@host http://localhost:8080
/*
## Get All Events
*/
###
# @name events
GET /api/events
/*
## Get Event By ID
*/
###
# @ref events
# @name event_by_id
GET /api/events/{{ events[0]._id }}
/*
## Get Events by Specific Category
*/
###
# @name filtered_events
GET /api/events?category={{"volunteer"}}
/*
## Create an Event
*/
###
# @ref events
# @name create_event
POST /api/events
Content-Type: application/json

{
    "name": "Senior Center Tech Help Day",
    "category": "volunteer",
    "dateAndTime": "2025-07-10T13:30:00Z",
    "location": "Lifelong Senior Center, Ithaca, NY",
    "summary": "Assist seniors with learning basic technology skills.",
    "description": "Join us in bridging the digital divide by volunteering to help seniors with smartphones, tablets, and computers. Whether it's setting up email or teaching how to video chat with family, your time will make a big difference. No advanced tech experience needed—just patience and kindness.",
    "numberOfAttendees": 20,
    "price": 0.00
}
/*
## Replace (Update) Existing Event
*/
###
# @ref events
# @name replace_event
PUT /api/events/{{ events[6]._id }}
Content-Type: application/json

{
  "name": "Ithaca Wellness & Outreach Day",
  "category": "volunteer",
  "dateAndTime": "2025-07-03T08:30:00Z",
  "location": "Cayuga Waterfront Trail, Ithaca, NY",
  "summary": "A community 5K walk that promotes wellness and volunteer action for local clinics.",
  "description": "Take part in a scenic 5K walk along the Cayuga Waterfront Trail. After the walk, volunteers can assist with setting up wellness booths, distributing health kits, or guiding participants. The event fosters both physical well-being and community service. Hydration stations, music, and free wellness giveaways will be available for all attendees.",
  "numberOfAttendees": 150,
  "price": 10.00
}
/*
## Modify (Update) Existing Event
*/
###
# @ref events
# @name modify_event
PATCH /api/events/{{ events[0]._id }}
Content-Type: application/json

{
    "numberOfAttendees": 100,
    "location": "Cascadilla Park, Ithaca, NY"
}
/*
## Delete Event
*/
###
# @ref events
# @name delete_event
DELETE /api/events/{{ events[7]._id }}
/*
## RSVP to an Event
*/
###
# @ref events
# @name rsvp_event
POST /api/events/{{ events[15]._id }}/rsvp
/*
## Cancel RSVP to an Event
*/
###
# @ref events
# @name cancel_rsvp
POST /api/events/{{ events[15]._id }}/cancel-rsvp
/*
### Text Search Only
*/
###
# @ref events
# @name text_search
GET /api/events?q=community
/*
### Text Search + Filter
*/
###
# @ref events
# @name text_search_and_filter
GET /api/events?q=community&category=volunteer