/*
## Test the Server API
*/
@host http://localhost:8080
/*
### Get All Events
*/
###
# @name events
GET /api/events

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 15189
etag: W/"3b55-eDray1jT2CQA4ZoA9XvkIpIdYe8"
date: Sun, 27 Apr 2025 20:53:31 GMT
connection: close
/*
### Get Event By ID
*/
###
# @ref events
# @name event_by_id
GET /api/events/{{ events[0]._id }}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 840
etag: W/"348-pOuujCcJbyp0q5MWe4CPyljPJlI"
date: Sun, 27 Apr 2025 20:53:33 GMT
connection: close
/*
### Get Events by Specific Category
*/
###
# @name filtered_events
GET /api/events?category={{"volunteer"}}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 2855
etag: W/"b27-K5xb7ub8AK5xvJP5pVGl77k9R+w"
date: Sun, 27 Apr 2025 20:53:37 GMT
connection: close
/*
### Create an Event
*/
###
# @ref events
# @name create_event
POST /api/events
Content-Type: application/json

{
    "name": "Senior Center Tech Help Day",
    "category": "volunteer",
    "dateAndTime": "2025-07-10T13:30:00Z",
    "location": "Lifelong Senior Center, Ithaca, NY",
    "summary": "Assist seniors with learning basic technology skills.",
    "description": "Join us in bridging the digital divide by volunteering to help seniors with smartphones, tablets, and computers. Whether it's setting up email or teaching how to video chat with family, your time will make a big difference. No advanced tech experience needed—just patience and kindness.",
    "numberOfAttendees": 20,
    "price": 0.00
}

HTTP/1.1 201  - Created
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 583
etag: W/"247-YUR75Jdj2Iw6mVVM4Fef5HHPnLc"
date: Sun, 27 Apr 2025 20:53:40 GMT
connection: close
/*
### Replace (Update) Existing Event
*/
###
# @ref events
# @name replace_event
PUT /api/events/{{ events[6]._id }}
Content-Type: application/json

{
  "name": "Ithaca Wellness & Outreach Day",
  "category": "volunteer",
  "dateAndTime": "2025-07-03T08:30:00Z",
  "location": "Cayuga Waterfront Trail, Ithaca, NY",
  "summary": "A community 5K walk that promotes wellness and volunteer action for local clinics.",
  "description": "Take part in a scenic 5K walk along the Cayuga Waterfront Trail. After the walk, volunteers can assist with setting up wellness booths, distributing health kits, or guiding participants. The event fosters both physical well-being and community service. Hydration stations, music, and free wellness giveaways will be available for all attendees.",
  "numberOfAttendees": 150,
  "price": 10.00
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 674
etag: W/"2a2-DpXY84QTuSqhSYYf5oqFFf/T1us"
date: Sun, 27 Apr 2025 20:53:41 GMT
connection: close
/*
### Modify (Update) Existing Event
*/
###
# @ref events
# @name modify_event
PATCH /api/events/{{ events[0]._id }}
Content-Type: application/json

{
    "numberOfAttendees": 100,
    "location": "Cascadilla Park, Ithaca, NY"
}

HTTP/1.1 404  - Not Found
x-powered-by: Express
access-control-allow-origin: *
date: Sun, 27 Apr 2025 20:53:44 GMT
connection: close
content-length: 0
/*
### Delete Event
*/
###
# @ref events
# @name delete_event
DELETE /api/events/{{ events[7]._id }}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
date: Sun, 27 Apr 2025 20:53:48 GMT
connection: close
content-length: 0
/*
### RSVP to an Event
*/
###
# @ref events
# @name rsvp_event
POST /api/events/{{ events[15]._id }}/rsvp

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
date: Sun, 27 Apr 2025 20:53:49 GMT
connection: close
content-length: 0
/*
### Cancel RSVP to an Event
*/
###
# @ref events
# @name cancel_rsvp
POST /api/events/{{ events[15]._id }}/cancel-rsvp

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
date: Sun, 27 Apr 2025 20:53:51 GMT
connection: close
content-length: 0
/*
### Text Search Only
*/
###
# @ref events
# @name text_search
GET /api/events?q=food

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 4642
etag: W/"1222-8DFnumJ3UROsXU3b95vzMAXnrug"
date: Sun, 27 Apr 2025 20:53:53 GMT
connection: close
/*
### Text Search + Filter
*/
###
# @ref events
# @name text_search_and_filter
GET /api/events?q=food&category=socials

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 1604
etag: W/"644-h+wJFHLfhTL2ZxZN4yvkiBaqJuY"
date: Sun, 27 Apr 2025 20:53:55 GMT
connection: close